version: 1.0.{build}
image: Visual Studio 2017
build_script:
- ps: .\build.ps1
deploy:
- provider: NuGet
  api_key:
    secure: 7MeFqw0NEAHvHpIWSp9+LL+LjVk8eaOVItwpYTuNf8eQP7f7IW7cr9t8S1XU42/S
  on:
    appveyor_repo_tag: true